name: node CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Project
        env:
          vercel_port: ${{ secrets.PORT }}
          vercel_db: ${{ secrets.DATABASE }}
          vercel-gmail-host: ${{ secrets.GMAIL_HOST }}
          vercel-gmail-port: ${{ secrets.GMAIL_PORT }}
          vercel-gmail-user: ${{ secrets.GMAIL_USER }}
          vercel-app-password: ${{ secrets.APP_PASSWORD }}
        run: npm run build

  deploy:
    name: Deploy to Vercel
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        env:
          vercel-port: ${{ secrets.PORT }}
          vercel-db: ${{ secrets.DATABASE }}
          vercel-gmail-host: ${{ secrets.GMAIL_HOST }}
          vercel-gmail-port: ${{ secrets.GMAIL_PORT }}
          vercel-gmail-user: ${{ secrets.GMAIL_USER }}
          vercel-app-password: ${{ secrets.APP_PASSWORD }}
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
